package transactions.core.dao;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "transactionErrorLogs")
public class TransactionErrorLogs {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String creditId;
	@DynamoDBAttribute
	private String information;
	@DynamoDBAttribute
	private String result;
	@DynamoDBAttribute
	private String numberIdBorrower;
	@DynamoDBAttribute
	private String numberIdLender;
	@DynamoDBAttribute
	private String typeTx;
	LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
	@DynamoDBAttribute
	private String dateSaveBD = dateTime.format(dtformat);
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCreditId() {
		return creditId;
	}
	public void setCreditId(String creditId) {
		this.creditId = creditId;
	}
	public String getInformation() {
		return information;
	}
	public void setInformation(String information) {
		this.information = information;
	}
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getNumberIdBorrower() {
		return numberIdBorrower;
	}
	public void setNumberIdBorrower(String numberIdBorrower) {
		this.numberIdBorrower = numberIdBorrower;
	}
	public String getNumberIdLender() {
		return numberIdLender;
	}
	public void setNumberIdLender(String numberIdLender) {
		this.numberIdLender = numberIdLender;
	}
	public String getTypeTx() {
		return typeTx;
	}
	public void setTypeTx(String typeTx) {
		this.typeTx = typeTx;
	}
	public String getDateSaveBD() {
		return dateSaveBD;
	}
	public void setDateSaveBD(String dateSaveBD) {
		this.dateSaveBD = dateSaveBD;
	}
	
	public TransactionErrorLogs() {
		super();
	}
	@Override
	public String toString() {
		return "{\"id\":\"" + id + "\", \"creditId\":\"" + creditId + "\", \"information\":\"" + information
				+ "\", \"result\":\"" + result + "\", \"numberIdBorrower\":\"" + numberIdBorrower
				+ "\", \"numberIdLender\":\"" + numberIdLender + "\", \"typeTx\":\"" + typeTx + "\", \"dateSaveBD\":\""
				+ dateSaveBD + "\"}";
	}
}
