package co.approbe.powwi.transaction.dao;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;


@DynamoDBTable(tableName = "borrower")
public class BorrowerForm {
	
		@DynamoDBAttribute
		@DynamoDBAutoGeneratedKey
		private String id;
		@DynamoDBTypeConvertedJson
		private Identification identification;
		@DynamoDBHashKey
		private String numberId;
		@DynamoDBAttribute
		private String cognitoId;
		@DynamoDBTypeConvertedJson 	
		private GeneralInformation generalInformation;
		@DynamoDBAttribute
		private double fv;
		@DynamoDBAttribute
		private int valuePay;
		@DynamoDBAttribute
		private int v;
		@DynamoDBTypeConvertedJson
		private CreditInformation creditInformation;
//		@DynamoDBTypeConvertedJson
//		private CompanyActivity companyActivity;
		@DynamoDBTypeConvertedJson
		private FinancialInformation financialInformation;
		@DynamoDBAttribute
		private String expeditionDate;
		@DynamoDBAttribute
		private String names;
		@DynamoDBAttribute
		private String lastName;
		@DynamoDBAttribute
		private String cellphone;
		@DynamoDBAttribute
		private String gender;
		@DynamoDBAttribute
		private String email;
		@DynamoDBAttribute
		private boolean habeas;
		@DynamoDBAttribute
		private boolean tyc;
		@DynamoDBAttribute
		private String firm;
		@DynamoDBAttribute
		private String password;
		@DynamoDBAttribute
		private String noticeApprobe;
		@DynamoDBAttribute
		private String urlFirm;
		
		
		@DynamoDBAttribute
		private double score=0;
		@DynamoDBAttribute
		private double ranking=0;
		@DynamoDBAttribute
		private double capacity=0;
		@DynamoDBAttribute
		private double scoreAcierta=0;
		@DynamoDBAttribute
		private double percentageCapacity=0;
		@DynamoDBAttribute
		private double feePlan=0;
		@DynamoDBAttribute
		private double rateApprobe=0;
		@DynamoDBAttribute
		private double feesApprobe=0;
		
		@DynamoDBAttribute
		private int apply=0;
		@DynamoDBAttribute
		private double approveValue=0;
		@DynamoDBAttribute
		private int paymentCapacity=0;
		@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	    @DynamoDBAttribute(attributeName = "peps")
		private boolean peps;
		@DynamoDBAttribute
		private int percentageApprobe=0;
		@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	    @DynamoDBAttribute(attributeName = "perp")
		private boolean perp=false;
		@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	    @DynamoDBAttribute(attributeName = "restrictList")
		private boolean restrictList=false;
		@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	    @DynamoDBAttribute(attributeName = "validId")
		private boolean validId=false;
		@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	    @DynamoDBAttribute(attributeName = "validPhone")
		private boolean validPhone=false;
		
		@DynamoDBAttribute
		private int active;
		@DynamoDBAttribute
		private String description;
		LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
		DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
		@DynamoDBAttribute
		private String dateSave = dateTime.format(dtformat);
		@DynamoDBAttribute
		private String dateSaveBD = dateTime.format(dtformat);
		@DynamoDBAttribute
		private String dataExperianS;
		@DynamoDBAttribute
		private String birthday;
		@DynamoDBAttribute
		private int age;
		@DynamoDBAttribute
		private String causalRechazo;
		@DynamoDBAttribute
		private String respuesta;
		
		
		//adiciono nuevas variables para las fechas 
		// dateActive0 fecha en el caso de que la solicitud fuera rechazada
		//dateActive1 fecha en el caso de que la solicitud fuera aprobada
		//dateActive4 fecha de paso a busqueda de fianaciador 
		//dateActive5 paso a firmas; 
		//dateActive6 desembolso 
		//dateActive7 el credito ya fue pagado
		
		@DynamoDBAttribute
		private String dateActive0;
		@DynamoDBAttribute
		private String dateActive1;
		@DynamoDBAttribute
		private String dateActive4;
		@DynamoDBAttribute
		private String dateActive5;
		@DynamoDBAttribute
		private String dateActive6;
		@DynamoDBAttribute
		private String dateActive7;
		@DynamoDBAttribute
		private String dateLastUpdate;
		
		@DynamoDBAttribute
		private String xml;
		
		@DynamoDBAttribute
		private int numUsuario;
		@DynamoDBAttribute
		private double income;
		@DynamoDBAttribute
		private double costs;
		@DynamoDBAttribute
		private double workingTime;
		@DynamoDBAttribute
		private double shareApprobe; 
		
		public double getShareApprobe() {
			return shareApprobe;
		}


		public void setShareApprobe(double shareApprobe) {
			this.shareApprobe = shareApprobe;
		}




		public double getWorkingTime() {
			return workingTime;
		}




		public void setWorkingTime(double workingTime) {
			this.workingTime = workingTime;
		}









		public double getCosts() {
			return costs;
		}




		public void setCosts(double costs) {
			this.costs = costs;
		}




		public double getIncome() {
			return income;
		}




		public void setIncome(double income) {
			this.income = income;
		}




		public int getNumUsuario() {
			return numUsuario;
		}




		public void setNumUsuario(int numUsuario) {
			this.numUsuario = numUsuario;
		}




		public String getDateActive4() {
			return dateActive4;
		}




		public void setDateActive4(String dateActive4) {
			this.dateActive4 = dateActive4;
		}




		public String getDateActive5() {
			return dateActive5;
		}




		public void setDateActive5(String dateActive5) {
			this.dateActive5 = dateActive5;
		}




		public String getDateActive6() {
			return dateActive6;
		}




		public void setDateActive6(String dateActive6) {
			this.dateActive6 = dateActive6;
		}




		public String getDateActive7() {
			return dateActive7;
		}




		public void setDateActive7(String dateActive7) {
			this.dateActive7 = dateActive7;
		}




		public String getDateActive0() {
			return dateActive0;
		}




		public void setDateActive0(String dateActive0) {
			this.dateActive0 = dateActive0;
		}




		public String getDateActive1() {
			return dateActive1;
		}




		public void setDateActive1(String dateActive1) {
			this.dateActive1 = dateActive1;
		}




		public String getDateLastUpdate() {
			return dateLastUpdate;
		}




		public void setDateLastUpdate(String dateLastUpdate) {
			this.dateLastUpdate = dateLastUpdate;
		}




		public String getId() {
			return id;
		}




		public void setId(String id) {
			this.id = id;
		}




		public Identification getIdentification() {
			return identification;
		}




		public void setIdentification(Identification identification) {
			this.identification = identification;
		}




		public String getNumberId() {
			return numberId;
		}




		public void setNumberId(String numberId) {
			this.numberId = numberId;
		}




		public String getCognitoId() {
			return cognitoId;
		}




		public void setCognitoId(String cognitoId) {
			this.cognitoId = cognitoId;
		}




		public GeneralInformation getGeneralInformation() {
			return generalInformation;
		}




		public void setGeneralInformation(GeneralInformation generalInformation) {
			this.generalInformation = generalInformation;
		}




		public double getFv() {
			return fv;
		}




		public void setFv(double fv) {
			this.fv = fv;
		}




		public int getValuePay() {
			return valuePay;
		}




		public void setValuePay(int valuePay) {
			this.valuePay = valuePay;
		}




		public int getV() {
			return v;
		}




		public void setV(int v) {
			this.v = v;
		}




		public CreditInformation getCreditInformation() {
			return creditInformation;
		}




		public void setCreditInformation(CreditInformation creditInformation) {
			this.creditInformation = creditInformation;
		}



		public FinancialInformation getFinancialInformation() {
			return financialInformation;
		}




		public void setFinancialInformation(FinancialInformation financialInformation) {
			this.financialInformation = financialInformation;
		}



		public String getExpeditionDate() {
			return expeditionDate;
		}




		public void setExpeditionDate(String expeditionDate) {
			this.expeditionDate = expeditionDate;
		}




		public String getNames() {
			return names;
		}




		public void setNames(String names) {
			this.names = names;
		}




		public String getLastName() {
			return lastName;
		}




		public void setLastName(String lastName) {
			this.lastName = lastName;
		}




		public String getCellphone() {
			return cellphone;
		}




		public void setCellphone(String cellphone) {
			this.cellphone = cellphone;
		}




		public String getGender() {
			return gender;
		}




		public void setGender(String gender) {
			this.gender = gender;
		}




		public String getEmail() {
			return email;
		}




		public void setEmail(String email) {
			this.email = email;
		}




		public boolean isHabeas() {
			return habeas;
		}




		public void setHabeas(boolean habeas) {
			this.habeas = habeas;
		}




		public boolean isTyc() {
			return tyc;
		}




		public void setTyc(boolean tyc) {
			this.tyc = tyc;
		}




		public String getFirm() {
			return firm;
		}




		public void setFirm(String firm) {
			this.firm = firm;
		}




		public String getPassword() {
			return password;
		}




		public void setPassword(String password) {
			this.password = password;
		}




		public String getNoticeApprobe() {
			return noticeApprobe;
		}




		public void setNoticeApprobe(String noticeApprobe) {
			this.noticeApprobe = noticeApprobe;
		}




		public String getUrlFirm() {
			return urlFirm;
		}




		public void setUrlFirm(String urlFirm) {
			this.urlFirm = urlFirm;
		}




		public double getScore() {
			return score;
		}




		public void setScore(double score) {
			this.score = score;
		}




		public double getRanking() {
			return ranking;
		}




		public void setRanking(double ranking) {
			this.ranking = ranking;
		}




		public double getCapacity() {
			return capacity;
		}




		public void setCapacity(double capacity) {
			this.capacity = capacity;
		}




		public double getScoreAcierta() {
			return scoreAcierta;
		}




		public void setScoreAcierta(double scoreAcierta) {
			this.scoreAcierta = scoreAcierta;
		}




		public double getPercentageCapacity() {
			return percentageCapacity;
		}




		public void setPercentageCapacity(double percentageCapacity) {
			this.percentageCapacity = percentageCapacity;
		}




		public double getFeePlan() {
			return feePlan;
		}




		public void setFeePlan(double feePlan) {
			this.feePlan = feePlan;
		}




		public double getRateApprobe() {
			return rateApprobe;
		}




		public void setRateApprobe(double rateApprobe) {
			this.rateApprobe = rateApprobe;
		}




		public double getFeesApprobe() {
			return feesApprobe;
		}




		public void setFeesApprobe(double feesApprobe) {
			this.feesApprobe = feesApprobe;
		}




		public int getApply() {
			return apply;
		}




		public void setApply(int apply) {
			this.apply = apply;
		}




		public double getApproveValue() {
			return approveValue;
		}




		public void setApproveValue(double approveValue) {
			this.approveValue = approveValue;
		}




		public int getPaymentCapacity() {
			return paymentCapacity;
		}




		public void setPaymentCapacity(int paymentCapacity) {
			this.paymentCapacity = paymentCapacity;
		}




		public boolean isPeps() {
			return peps;
		}




		public void setPeps(boolean peps) {
			this.peps = peps;
		}




		public int getPercentageApprobe() {
			return percentageApprobe;
		}




		public void setPercentageApprobe(int percentageApprobe) {
			this.percentageApprobe = percentageApprobe;
		}




		public boolean isPerp() {
			return perp;
		}




		public void setPerp(boolean perp) {
			this.perp = perp;
		}




		public boolean isRestrictList() {
			return restrictList;
		}




		public void setRestrictList(boolean restrictList) {
			this.restrictList = restrictList;
		}




		public boolean isValidId() {
			return validId;
		}




		public void setValidId(boolean validId) {
			this.validId = validId;
		}




		public boolean isValidPhone() {
			return validPhone;
		}




		public void setValidPhone(boolean validPhone) {
			this.validPhone = validPhone;
		}




		public int getActive() {
			return active;
		}




		public void setActive(int active) {
			this.active = active;
		}




		public String getDescription() {
			return description;
		}




		public void setDescription(String description) {
			this.description = description;
		}




		public String getDateSave() {
			return dateSave;
		}




		public void setDateSave(String dateSave) {
			this.dateSave = dateSave;
		}




		public String getDateSaveBD() {
			return dateSaveBD;
		}




		public void setDateSaveBD(String dateSaveBD) {
			this.dateSaveBD = dateSaveBD;
		}



		public String getBirthday() {
			return birthday;
		}




		public void setBirthday(String birthday) {
			this.birthday = birthday;
		}




		public int getAge() {
			return age;
		}




		public void setAge(int age) {
			this.age = age;
		}




		public String getCausalRechazo() {
			return causalRechazo;
		}




		public void setCausalRechazo(String causalRechazo) {
			this.causalRechazo = causalRechazo;
		}




		public String getRespuesta() {
			return respuesta;
		}




		public void setRespuesta(String respuesta) {
			this.respuesta = respuesta;
		}




		public String getXml() {
			return xml;
		}




		public void setXml(String xml) {
			this.xml = xml;
		}




		public String getDataExperianS() {
			return dataExperianS;
		}




		public void setDataExperianS(String dataExperianS) {
			this.dataExperianS = dataExperianS;
		}




		public BorrowerForm() {
			super();
		}


		public BorrowerForm(String id, Identification identification, String numberId, String cognitoId,
				GeneralInformation generalInformation, double fv, int valuePay, int v,
				CreditInformation creditInformation, FinancialInformation financialInformation, String expeditionDate,
				String names, String lastName, String cellphone, String gender, String email, boolean habeas,
				boolean tyc, String firm, String password, String noticeApprobe, String urlFirm, double score,
				double ranking, double capacity, double scoreAcierta, double percentageCapacity, double feePlan,
				double rateApprobe, double feesApprobe, int apply, double approveValue, int paymentCapacity,
				boolean peps, int percentageApprobe, boolean perp, boolean restrictList, boolean validId,
				boolean validPhone, int active, String description, String dateSave, String dateSaveBD,
				String dataExperianS, String birthday, int age, String causalRechazo, String respuesta,
				String dateActive0, String dateActive1, String dateActive4, String dateActive5, String dateActive6,
				String dateActive7, String dateLastUpdate, String xml, int numUsuario, double income, double costs,
				double workingTime, double shareApprobe) {
			super();
			this.id = id;
			this.identification = identification;
			this.numberId = numberId;
			this.cognitoId = cognitoId;
			this.generalInformation = generalInformation;
			this.fv = fv;
			this.valuePay = valuePay;
			this.v = v;
			this.creditInformation = creditInformation;
			this.financialInformation = financialInformation;
			this.expeditionDate = expeditionDate;
			this.names = names;
			this.lastName = lastName;
			this.cellphone = cellphone;
			this.gender = gender;
			this.email = email;
			this.habeas = habeas;
			this.tyc = tyc;
			this.firm = firm;
			this.password = password;
			this.noticeApprobe = noticeApprobe;
			this.urlFirm = urlFirm;
			this.score = score;
			this.ranking = ranking;
			this.capacity = capacity;
			this.scoreAcierta = scoreAcierta;
			this.percentageCapacity = percentageCapacity;
			this.feePlan = feePlan;
			this.rateApprobe = rateApprobe;
			this.feesApprobe = feesApprobe;
			this.apply = apply;
			this.approveValue = approveValue;
			this.paymentCapacity = paymentCapacity;
			this.peps = peps;
			this.percentageApprobe = percentageApprobe;
			this.perp = perp;
			this.restrictList = restrictList;
			this.validId = validId;
			this.validPhone = validPhone;
			this.active = active;
			this.description = description;
			this.dateSave = dateSave;
			this.dateSaveBD = dateSaveBD;
			this.dataExperianS = dataExperianS;
			this.birthday = birthday;
			this.age = age;
			this.causalRechazo = causalRechazo;
			this.respuesta = respuesta;
			this.dateActive0 = dateActive0;
			this.dateActive1 = dateActive1;
			this.dateActive4 = dateActive4;
			this.dateActive5 = dateActive5;
			this.dateActive6 = dateActive6;
			this.dateActive7 = dateActive7;
			this.dateLastUpdate = dateLastUpdate;
			this.xml = xml;
			this.numUsuario = numUsuario;
			this.income = income;
			this.costs = costs;
			this.workingTime = workingTime;
			this.shareApprobe = shareApprobe;
		}


		@Override
		public String toString() {
			return "{\"id\":\"" + id + "\", \"identification\":\"" + identification + "\", \"numberId\":\"" + numberId
					+ "\", \"cognitoId\":\"" + cognitoId + "\", \"generalInformation\":\"" + generalInformation
					+ "\", \"fv\":\"" + fv + "\", \"valuePay\":\"" + valuePay + "\", \"v\":\"" + v
					+ "\", \"creditInformation\":\"" + creditInformation + "\", \"financialInformation\":\""
					+ financialInformation + "\", \"expeditionDate\":\"" + expeditionDate + "\", \"names\":\"" + names
					+ "\", \"lastName\":\"" + lastName + "\", \"cellphone\":\"" + cellphone + "\", \"gender\":\""
					+ gender + "\", \"email\":\"" + email + "\", \"habeas\":\"" + habeas + "\", \"tyc\":\"" + tyc
					+ "\", \"firm\":\"" + firm + "\", \"password\":\"" + password + "\", \"noticeApprobe\":\""
					+ noticeApprobe + "\", \"urlFirm\":\"" + urlFirm + "\", \"score\":\"" + score + "\", \"ranking\":\""
					+ ranking + "\", \"capacity\":\"" + capacity + "\", \"scoreAcierta\":\"" + scoreAcierta
					+ "\", \"percentageCapacity\":\"" + percentageCapacity + "\", \"feePlan\":\"" + feePlan
					+ "\", \"rateApprobe\":\"" + rateApprobe + "\", \"feesApprobe\":\"" + feesApprobe
					+ "\", \"apply\":\"" + apply + "\", \"approveValue\":\"" + approveValue
					+ "\", \"paymentCapacity\":\"" + paymentCapacity + "\", \"peps\":\"" + peps
					+ "\", \"percentageApprobe\":\"" + percentageApprobe + "\", \"perp\":\"" + perp
					+ "\", \"restrictList\":\"" + restrictList + "\", \"validId\":\"" + validId
					+ "\", \"validPhone\":\"" + validPhone + "\", \"active\":\"" + active + "\", \"description\":\""
					+ description + "\", \"dateSave\":\"" + dateSave + "\", \"dateSaveBD\":\"" + dateSaveBD
					+ "\", \"dataExperianS\":\"" + dataExperianS + "\", \"birthday\":\"" + birthday + "\", \"age\":\""
					+ age + "\", \"causalRechazo\":\"" + causalRechazo + "\", \"respuesta\":\"" + respuesta
					+ "\", \"dateActive0\":\"" + dateActive0 + "\", \"dateActive1\":\"" + dateActive1
					+ "\", \"dateActive4\":\"" + dateActive4 + "\", \"dateActive5\":\"" + dateActive5
					+ "\", \"dateActive6\":\"" + dateActive6 + "\", \"dateActive7\":\"" + dateActive7
					+ "\", \"dateLastUpdate\":\"" + dateLastUpdate + "\", \"xml\":\"" + xml + "\", \"numUsuario\":\""
					+ numUsuario + "\", \"income\":\"" + income + "\", \"costs\":\"" + costs + "\", \"workingTime\":\""
					+ workingTime + "\", \"shareApprobe\":\"" + shareApprobe + "\"}";
		}

		

	}
