package co.approbe.powwi.transaction.dao;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="bankTransactions")
public class LogTx {
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String numberId;
	@DynamoDBAttribute
	private String responseTx;
	@DynamoDBAttribute
	private String requestTx;
	LocalDateTime dateTime = LocalDateTime.now(ZoneOffset.of("-05:00"));
	DateTimeFormatter dtformat = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
	@DynamoDBAttribute
	private String dateUpdate=dateTime.format(dtformat);;
	@DynamoDBAttribute
	private String status;
	@DynamoDBAttribute
	private String resultTx;
	@DynamoDBAttribute
	private String amountTx;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getNumberId() {
		return numberId;
	}
	public void setNumberId(String numberId) {
		this.numberId = numberId;
	}
	public String getResponseTx() {
		return responseTx;
	}
	public void setResponseTx(String responseTx) {
		this.responseTx = responseTx;
	}
	public String getRequestTx() {
		return requestTx;
	}
	public void setRequestTx(String requestTx) {
		this.requestTx = requestTx;
	}
	public String getDateUpdate() {
		return dateUpdate;
	}
	public void setDateUpdate(String dateUpdate) {
		this.dateUpdate = dateUpdate;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getResultTx() {
		return resultTx;
	}
	public void setResultTx(String resultTx) {
		this.resultTx = resultTx;
	}
	public String getAmountTx() {
		return amountTx;
	}
	public void setAmountTx(String amountTx) {
		this.amountTx = amountTx;
	}
	public LogTx(String id, String numberId, String responseTx, String requestTx, String dateUpdate, String status,
			String resultTx, String amountTx) {
		super();
		this.id = id;
		this.numberId = numberId;
		this.responseTx = responseTx;
		this.requestTx = requestTx;
		this.dateUpdate = dateUpdate;
		this.status = status;
		this.resultTx = resultTx;
		this.amountTx = amountTx;
	}
	public LogTx() {
		super();
	}
	
	
	
	
	

}
